(()=>{
const $=id=>document.getElementById(id);const input=$('demoInput'),run=$('demoRun'),result=$('demoResult'),status=$('demoStatus');let generation=0;
const examples={booking:'Hi, I’d like to book a consultation next week. Do you have any afternoon appointments?',quote:'Could you send a quote for setting up client intake for our five-person team? We currently use a spreadsheet.',documents:'I submitted my application but I’m not sure which documents are still missing. Can you check?'};
const plans={booking:['Appointment request','Confirm availability','Thanks for your interest in a consultation. What day and time zone work best for you? We’ll check availability and confirm a time.'],quote:['Quote request','Collect scope details','Thanks for getting in touch. Could you share the process you want improved, the tools you use, and your preferred timeline? We’ll review the scope before preparing a quote.'],documents:['Document question','Check required documents','Thanks for checking. Please let us know which application or process this concerns. Our team will check the requirements and confirm what is still needed.'],general:['General inquiry','Ask for more context','Thanks for reaching out. Could you tell us a little more about what you need? Our team will review the details and confirm the next step.']};
function reset(){generation++;run.disabled=false;run.textContent='Run the workflow';result.hidden=true;status.textContent='Ready for your sample inquiry.';document.querySelectorAll('[data-step]').forEach(x=>x.className='');$('approvalStatus').textContent='Waiting for your review. Nothing will be sent.';$('approveReply').disabled=false;$('approveReply').textContent='Approve this sample';}
$('demoType').onchange=()=>{reset();input.value=examples[$('demoType').value]};$('demoReset').onclick=()=>{reset();input.value=examples[$('demoType').value]};
run.onclick=async()=>{reset();const value=input.value.trim();if(value.length<12){status.textContent='Add at least 12 characters so there is a request to review.';input.focus();return}const token=generation;run.disabled=true;run.textContent='Running…';const words=value.toLowerCase();const kind=/document|application|missing/.test(words)?'documents':/quote|cost|price|budget/.test(words)?'quote':/book|appointment|consult|schedule/.test(words)?'booking':'general';const messages=['Receiving your sample inquiry…','Sorting the request using demo rules…','Preparing a suggested response…','Ready for your review. Nothing has been sent.'];for(let i=0;i<4;i++){if(token!==generation)return;document.querySelectorAll('[data-step]').forEach((el,n)=>el.className=n<i?'done':n===i?'active':'');status.textContent=messages[i];await new Promise(r=>setTimeout(r,550));}if(token!==generation)return;const p=plans[kind];$('requestType').textContent=p[0];$('nextStep').textContent=p[1];$('draftReply').value=p[2];result.hidden=false;run.disabled=false;run.textContent='Run again';};
$('approveReply').onclick=()=>{if(!$('draftReply').value.trim()){$('approvalStatus').textContent='Add a reply before approving.';return}$('approvalStatus').textContent='Sample approved. In a connected workflow, this is where your approved action could run. No message was sent.';$('approveReply').textContent='Sample approved';$('approveReply').disabled=true;};
$('draftReply').oninput=()=>{$('approveReply').disabled=false;$('approveReply').textContent='Approve this sample';$('approvalStatus').textContent='Edited reply: review again before approving.'};
$('copyReply').onclick=async()=>{try{await navigator.clipboard.writeText($('draftReply').value);$('approvalStatus').textContent='Reply copied. Nothing has been sent.'}catch{$('draftReply').focus();$('draftReply').select();$('approvalStatus').textContent='Select and copy the reply from the field above.'}};
})();
